name: Automatically deploy to Alpha
on:
  
  # Run this AFTER the unit test job finishes
  workflow_run:
    # Must be the same as in unittests.yml, cypresstests.yml
    workflows: ["Unit tests", "Cypress tests"]
    # Make this main to activate auto-deploy
    branches: [none]
    types:
      - completed
jobs:
  deploy:
    # Deploy ONLY IF the tests actually succeeded (if they failed, we don't wanna deploy)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: 'Install Heroku CLI'
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # update when create heroku app
          heroku_app_name: jamjoum-alpha
          # update when create heroku app
          heroku_email: fake-mail@mail.com
